### ISSUE TITLE
Bug in Sha1 hashing

### ISSUE THREAD

**Issue by MrBoboGet** [Chocobo1/Hash#3]
Got an invalid hash value when hashing the contents of this file I have attached. Hash value with this Sha1 implementation: 87e4ce7bde2fc706fe982e26f118c16333180d96. Hex value I got from openssl command line: 004c318fbda1d2172f3fec228f509c06b9cbaf91. I also replaced the sha1 implementation to doublecheck that it wasn't my input that was wrong, and got the correct hash value with that. The occasional wrong MAC's I got in my TLS implementation has also dissapeared since I replaced the hash function. I can only assume that it has to be some obscure bug in this library's sha1 implementation, as it works fine 99% of the time. Compiled on windows x86-64 with MSVC and C++17.
I have also attached exactly what code I used to replicate the bug.  (DebugHash.txt should be read as binary data).
[DebugHash.txt](https://github.com/Chocobo1/Hash/files/6002865/DebugHash.txt)
[WrongHash.txt](https://github.com/Chocobo1/Hash/files/6002869/WrongHash.txt)

**Comment by Chocobo1** [comment]
Hi, I consider it fixed in 267cca943b726457d12793c7b95cc2c2ab79b23f, would you please verify?

**Comment by MrBoboGet** [comment]
Works for my test cases and no longer gives wrong MAC on url's that previously had problems, seems fixed to me.

**Comment by Chocobo1** [comment]
Great! I'm closing this then.
