### ISSUE TITLE
Worse library ever

### ISSUE THREAD

**Issue by 0zirix** [Chocobo1/Hash#5]
This library is not usable::

MACRO is failing: USE_STD_SPAN_CHOCOBO1_HASH

Whatever you define it, it will trigger an error, telling you that std::span is not defined
-> Enable C++20 to get this feature: still failing lol.

Weird namspaces overwritten at the top on include for no reasons.

And the best for the end:

Line 376 of md5.h: iMax is NEVER defined anywhere.

I'm wondering how you can write such a lib, which that many lines of code, without encountering this fearking error !!!

I will never try to use that again, complete waste of time.

**Comment by Chocobo1** [comment]
Ohh, a toxic comment...

>Whatever you define it, it will trigger an error, telling you that std::span is not defined

It is an auto detection. In your own code, you are not supposed to mess with the macro, just ignore it completely.

>-> Enable C++20 to get this feature: still failing lol.

Do your compiler support `std::span`? If not, stick with `gsl`.

>Line 376 of md5.h: iMax is NEVER defined anywhere.

Is that a joke? I completely missed it.
https://github.com/Chocobo1/Hash/blob/9613e0a0da1914834593f510c4caef6eae20f73c/src/md5.h#L382

>I'm wondering how you can write such a lib, which that many lines of code, without encountering this fearking error !!!

Magic.

>I will never try to use that again, complete waste of time.

I was willing to help and but I suppose you really mean it, pity. Closing.
