### ISSUE TITLE
Issue when including from header file

### ISSUE THREAD

**Issue by PiootrK** [Chocobo1/Hash#7]
I tried including "sha1.h" from header file, which then gets included in several other places. During linking multiple methods from SHA1 are detected, in every file that has the include. I understand why this happens, but it makes using the library in anything but a simple project impossible.

**Comment by Chocobo1** [comment]
Thanks for reporting!
Addressed it in 6d48d2a72fc25ba37bda72d7363bbddd95e2ace5.

**Comment by PiootrK** [comment]
Wow, that was fast. Thanks!
